FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install --include=dev
COPY . .
ARG VITE_FASTLINK_API_URL
ARG VITE_FASTLINK_ENVIRONMENT=SANDBOX
ARG RAILWAY_GIT_COMMIT_SHA=unknown
ENV VITE_FASTLINK_API_URL=$VITE_FASTLINK_API_URL
ENV VITE_FASTLINK_ENVIRONMENT=$VITE_FASTLINK_ENVIRONMENT
ENV VITE_FASTLINK_BUILD_SHA=$RAILWAY_GIT_COMMIT_SHA
ENV NITRO_PRESET=node_server
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV NITRO_HOST=0.0.0.0
ENV PORT=8080
ENV NITRO_PORT=8080
COPY --from=builder /app/.output ./.output
USER node
EXPOSE 8080
CMD ["node", ".output/server/index.mjs"]
