/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MerchantPayRouteImport } from './routes/merchant-pay'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CardPayRouteImport } from './routes/card-pay'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsFiatRouteImport } from './routes/assets.fiat'
import { Route as AssetsDigitalRouteImport } from './routes/assets.digital'
import { Route as AssetsCardsRouteImport } from './routes/assets.cards'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantPayRoute = MerchantPayRouteImport.update({
  id: '/merchant-pay',
  path: '/merchant-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CardPayRoute = CardPayRouteImport.update({
  id: '/card-pay',
  path: '/card-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsFiatRoute = AssetsFiatRouteImport.update({
  id: '/assets/fiat',
  path: '/assets/fiat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsDigitalRoute = AssetsDigitalRouteImport.update({
  id: '/assets/digital',
  path: '/assets/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsCardsRoute = AssetsCardsRouteImport.update({
  id: '/assets/cards',
  path: '/assets/cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-pay': typeof CardPayRoute
  '/cards': typeof CardsRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/merchant-pay': typeof MerchantPayRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/assets/cards': typeof AssetsCardsRoute
  '/assets/digital': typeof AssetsDigitalRoute
  '/assets/fiat': typeof AssetsFiatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-pay': typeof CardPayRoute
  '/cards': typeof CardsRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/merchant-pay': typeof MerchantPayRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/assets/cards': typeof AssetsCardsRoute
  '/assets/digital': typeof AssetsDigitalRoute
  '/assets/fiat': typeof AssetsFiatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-pay': typeof CardPayRoute
  '/cards': typeof CardsRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/merchant-pay': typeof MerchantPayRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/withdraw': typeof WithdrawRoute
  '/assets/cards': typeof AssetsCardsRoute
  '/assets/digital': typeof AssetsDigitalRoute
  '/assets/fiat': typeof AssetsFiatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card-pay'
    | '/cards'
    | '/connect'
    | '/convert'
    | '/deposit'
    | '/history'
    | '/kyc'
    | '/merchant-pay'
    | '/pay'
    | '/profile'
    | '/transfer'
    | '/withdraw'
    | '/assets/cards'
    | '/assets/digital'
    | '/assets/fiat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card-pay'
    | '/cards'
    | '/connect'
    | '/convert'
    | '/deposit'
    | '/history'
    | '/kyc'
    | '/merchant-pay'
    | '/pay'
    | '/profile'
    | '/transfer'
    | '/withdraw'
    | '/assets/cards'
    | '/assets/digital'
    | '/assets/fiat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/card-pay'
    | '/cards'
    | '/connect'
    | '/convert'
    | '/deposit'
    | '/history'
    | '/kyc'
    | '/merchant-pay'
    | '/pay'
    | '/profile'
    | '/transfer'
    | '/withdraw'
    | '/assets/cards'
    | '/assets/digital'
    | '/assets/fiat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CardPayRoute: typeof CardPayRoute
  CardsRoute: typeof CardsRoute
  ConnectRoute: typeof ConnectRoute
  ConvertRoute: typeof ConvertRoute
  DepositRoute: typeof DepositRoute
  HistoryRoute: typeof HistoryRoute
  KycRoute: typeof KycRoute
  MerchantPayRoute: typeof MerchantPayRoute
  PayRoute: typeof PayRoute
  ProfileRoute: typeof ProfileRoute
  TransferRoute: typeof TransferRoute
  WithdrawRoute: typeof WithdrawRoute
  AssetsCardsRoute: typeof AssetsCardsRoute
  AssetsDigitalRoute: typeof AssetsDigitalRoute
  AssetsFiatRoute: typeof AssetsFiatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-pay': {
      id: '/merchant-pay'
      path: '/merchant-pay'
      fullPath: '/merchant-pay'
      preLoaderRoute: typeof MerchantPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-pay': {
      id: '/card-pay'
      path: '/card-pay'
      fullPath: '/card-pay'
      preLoaderRoute: typeof CardPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/fiat': {
      id: '/assets/fiat'
      path: '/assets/fiat'
      fullPath: '/assets/fiat'
      preLoaderRoute: typeof AssetsFiatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/digital': {
      id: '/assets/digital'
      path: '/assets/digital'
      fullPath: '/assets/digital'
      preLoaderRoute: typeof AssetsDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/cards': {
      id: '/assets/cards'
      path: '/assets/cards'
      fullPath: '/assets/cards'
      preLoaderRoute: typeof AssetsCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CardPayRoute: CardPayRoute,
  CardsRoute: CardsRoute,
  ConnectRoute: ConnectRoute,
  ConvertRoute: ConvertRoute,
  DepositRoute: DepositRoute,
  HistoryRoute: HistoryRoute,
  KycRoute: KycRoute,
  MerchantPayRoute: MerchantPayRoute,
  PayRoute: PayRoute,
  ProfileRoute: ProfileRoute,
  TransferRoute: TransferRoute,
  WithdrawRoute: WithdrawRoute,
  AssetsCardsRoute: AssetsCardsRoute,
  AssetsDigitalRoute: AssetsDigitalRoute,
  AssetsFiatRoute: AssetsFiatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
